//! Deterministic RNG for Falcon-512 testing
//! 
//! This module provides a deterministic random number generator
//! based on DRBG (Deterministic Random Bit Generator) for
//! reproducible testing, especially for NIST KAT validation.

use crate::shake::Shake256Context;
use rand::{RngCore, Error as RandError};
use alloc::vec::Vec;

/// Deterministic RNG using SHAKE256 as the underlying DRBG
pub struct DeterministicRng {
    /// Internal state
    state: Vec<u8>,
    /// Counter for additional entropy
    counter: u64,
    /// Buffer for generated bytes
    buffer: Vec<u8>,
    /// Current position in buffer
    buffer_pos: usize,
}

impl DeterministicRng {
    /// Create a new deterministic RNG with a seed
    pub fn new(seed: &[u8]) -> Self {
        let mut state = vec![0u8; 48];
        
        // Initialize state with seed
        let mut shake = Shake256Context::new();
        shake.update(b"DeterministicRNG.init");
        shake.update(seed);
        let mut reader = shake.finalize_xof();
        reader.read(&mut state);
        
        Self {
            state,
            counter: 0,
            buffer: Vec::new(),
            buffer_pos: 0,
        }
    }
    
    /// Create from a fixed seed for NIST KAT testing
    pub fn new_for_kat(seed: &[u8], personalization: &[u8]) -> Self {
        let mut state = vec![0u8; 48];
        
        // NIST-compliant initialization
        let mut shake = Shake256Context::new();
        shake.update(b"NIST.KAT.DRBG");
        shake.update(&(seed.len() as u32).to_le_bytes());
        shake.update(seed);
        shake.update(&(personalization.len() as u32).to_le_bytes());
        shake.update(personalization);
        let mut reader = shake.finalize_xof();
        reader.read(&mut state);
        
        Self {
            state,
            counter: 0,
            buffer: Vec::new(),
            buffer_pos: 0,
        }
    }
    
    /// Reseed the RNG with additional input
    pub fn reseed(&mut self, additional: &[u8]) {
        let mut shake = Shake256Context::new();
        shake.update(b"DeterministicRNG.reseed");
        shake.update(&self.state);
        shake.update(additional);
        shake.update(&self.counter.to_le_bytes());
        
        let mut new_state = vec![0u8; 48];
        let mut reader = shake.finalize_xof();
        reader.read(&mut new_state);
        self.state = new_state;
        self.counter = 0;
        self.buffer.clear();
        self.buffer_pos = 0;
    }
    
    /// Generate bytes deterministically
    fn generate(&mut self, dest: &mut [u8]) {
        // Update internal state
        self.counter += 1;
        
        let mut shake = Shake256Context::new();
        shake.update(b"DeterministicRNG.generate");
        shake.update(&self.state);
        shake.update(&self.counter.to_le_bytes());
        
        // Generate output
        let mut reader = shake.finalize_xof();
        reader.read(dest);
        
        // Update state for forward secrecy
        let mut shake2 = Shake256Context::new();
        shake2.update(b"DeterministicRNG.state");
        shake2.update(&self.state);
        shake2.update(&self.counter.to_le_bytes());
        let mut reader2 = shake2.finalize_xof();
        let mut new_state = vec![0u8; 48];
        reader2.read(&mut new_state);
        self.state = new_state;
    }
}

impl RngCore for DeterministicRng {
    fn next_u32(&mut self) -> u32 {
        let mut bytes = [0u8; 4];
        self.fill_bytes(&mut bytes);
        u32::from_le_bytes(bytes)
    }
    
    fn next_u64(&mut self) -> u64 {
        let mut bytes = [0u8; 8];
        self.fill_bytes(&mut bytes);
        u64::from_le_bytes(bytes)
    }
    
    fn fill_bytes(&mut self, dest: &mut [u8]) {
        let mut written = 0;
        
        // Use buffered bytes first
        if self.buffer_pos < self.buffer.len() {
            let available = self.buffer.len() - self.buffer_pos;
            let to_copy = available.min(dest.len());
            dest[..to_copy].copy_from_slice(&self.buffer[self.buffer_pos..self.buffer_pos + to_copy]);
            self.buffer_pos += to_copy;
            written = to_copy;
        }
        
        // Generate more if needed
        if written < dest.len() {
            let remaining = &mut dest[written..];
            
            if remaining.len() > 32 {
                // Large request: generate directly
                self.generate(remaining);
            } else {
                // Small request: refill buffer
                self.buffer.resize(64, 0);
                let buffer_ptr = self.buffer.as_mut_ptr();
                let buffer_len = self.buffer.len();
                // Create a temporary slice to avoid borrow conflict
                let buffer_slice = unsafe { 
                    core::slice::from_raw_parts_mut(buffer_ptr, buffer_len)
                };
                self.generate(buffer_slice);
                self.buffer_pos = 0;
                
                let to_copy = remaining.len();
                remaining.copy_from_slice(&self.buffer[..to_copy]);
                self.buffer_pos = to_copy;
            }
        }
    }
    
    fn try_fill_bytes(&mut self, dest: &mut [u8]) -> Result<(), RandError> {
        self.fill_bytes(dest);
        Ok(())
    }
}

/// Signing mode selector
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum SigningMode {
    /// Non-deterministic mode using system RNG (production)
    NonDeterministic,
    /// Deterministic mode using DRBG (testing)
    Deterministic,
    /// NIST KAT mode with fixed seed
    NistKat,
}

/// Configuration for deterministic signing
#[derive(Clone, Debug)]
pub struct DeterministicConfig {
    /// Signing mode
    pub mode: SigningMode,
    /// Seed for deterministic mode (ignored in non-deterministic mode)
    pub seed: Vec<u8>,
    /// Personalization string for NIST KAT
    pub personalization: Vec<u8>,
    /// Enable debug output
    pub debug: bool,
}

impl Default for DeterministicConfig {
    fn default() -> Self {
        Self {
            mode: SigningMode::NonDeterministic,
            seed: Vec::new(),
            personalization: Vec::new(),
            debug: false,
        }
    }
}

impl DeterministicConfig {
    /// Create config for non-deterministic signing
    pub fn non_deterministic() -> Self {
        Self::default()
    }
    
    /// Create config for deterministic signing with seed
    pub fn deterministic(seed: &[u8]) -> Self {
        Self {
            mode: SigningMode::Deterministic,
            seed: seed.to_vec(),
            personalization: Vec::new(),
            debug: false,
        }
    }
    
    /// Create config for NIST KAT testing
    pub fn nist_kat(seed: &[u8], personalization: &[u8]) -> Self {
        Self {
            mode: SigningMode::NistKat,
            seed: seed.to_vec(),
            personalization: personalization.to_vec(),
            debug: false,
        }
    }
    
    /// Create an RNG based on the configuration
    pub fn create_rng(&self) -> Box<dyn RngCore> {
        match self.mode {
            SigningMode::NonDeterministic => {
                // Use system RNG
                Box::new(rand::thread_rng())
            }
            SigningMode::Deterministic => {
                // Use deterministic RNG with seed
                Box::new(DeterministicRng::new(&self.seed))
            }
            SigningMode::NistKat => {
                // Use NIST KAT compliant RNG
                Box::new(DeterministicRng::new_for_kat(&self.seed, &self.personalization))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_deterministic_rng_reproducible() {
        let seed = b"test seed";
        
        let mut rng1 = DeterministicRng::new(seed);
        let mut rng2 = DeterministicRng::new(seed);
        
        let mut bytes1 = [0u8; 32];
        let mut bytes2 = [0u8; 32];
        
        rng1.fill_bytes(&mut bytes1);
        rng2.fill_bytes(&mut bytes2);
        
        assert_eq!(bytes1, bytes2, "Deterministic RNG should be reproducible");
    }
    
    #[test]
    fn test_deterministic_rng_different_seeds() {
        let mut rng1 = DeterministicRng::new(b"seed1");
        let mut rng2 = DeterministicRng::new(b"seed2");
        
        let mut bytes1 = [0u8; 32];
        let mut bytes2 = [0u8; 32];
        
        rng1.fill_bytes(&mut bytes1);
        rng2.fill_bytes(&mut bytes2);
        
        assert_ne!(bytes1, bytes2, "Different seeds should produce different output");
    }
    
    #[test]
    fn test_nist_kat_rng() {
        let seed = b"NIST seed";
        let pers = b"personalization";
        
        let mut rng = DeterministicRng::new_for_kat(seed, pers);
        
        // Generate some bytes
        let mut bytes = [0u8; 64];
        rng.fill_bytes(&mut bytes);
        
        // Should not be all zeros
        assert!(bytes.iter().any(|&b| b != 0));
    }
    
    #[test]
    fn test_config_modes() {
        // Non-deterministic
        let config1 = DeterministicConfig::non_deterministic();
        assert_eq!(config1.mode, SigningMode::NonDeterministic);
        
        // Deterministic
        let config2 = DeterministicConfig::deterministic(b"seed");
        assert_eq!(config2.mode, SigningMode::Deterministic);
        
        // NIST KAT
        let config3 = DeterministicConfig::nist_kat(b"seed", b"pers");
        assert_eq!(config3.mode, SigningMode::NistKat);
    }
}