// Self-consistency KAT vector generation and validation.
//
// WARNING — this module does NOT reproduce official NIST Falcon vectors.
// The genuine Falcon Round 3 KAT is driven by AES-256 CTR_DRBG (see
// `KAT/generator/katrng.c` in `falcon-round3.zip`); the seed-expansion below is
// an in-repo SHA-256 construction that matches no NIST protocol. Vectors made
// here only prove this implementation is self-consistent (sign→verify round
// trips), never that it conforms to the Falcon spec. For genuine upstream
// conformance, see `tests/falcon_upstream_kat.rs` + `test-vectors/falcon-upstream/`.
// `load_nist_kat_vectors()` therefore deliberately fails closed (NotImplemented).

use crate::drbg::NistCtrDrbg;
use crate::error::{Falcon512Error, Result};
use crate::{generate_keypair, verify, PublicKey, PrivateKey};
use metamui_sha2::Sha256Hasher;

use std::vec::Vec;

/// NIST KAT vector entry
#[derive(Debug, Clone)]
pub struct KatVector {
    pub count: usize,
    pub seed: [u8; 48],
    pub mlen: usize,
    pub msg: Vec<u8>,
    pub pk: Vec<u8>,
    pub sk: Vec<u8>,
    pub smlen: usize,
    pub sm: Vec<u8>,
}

/// Generate self-consistency KAT vectors for Falcon-512.
///
/// NOTE: this is an in-repo reproducible generator, NOT the NIST process. The
/// seed expansion (`generate_entropy_seed`/`update_seed`) is a local SHA-256
/// construction and does not match NIST's AES-CTR-DRBG KAT protocol, so the
/// output cannot equal official NIST vectors. Steps:
/// 1. Derive a per-iteration entropy seed (SHA-256, in-repo scheme)
/// 2. Drive a CTR_DRBG from it for all randomness
/// 3. Generate keypair
/// 4. Sign message
/// 5. Verify signature (round-trip self-consistency only)
pub fn generate_kat_vectors(num_vectors: usize) -> Result<Vec<KatVector>> {
    let mut vectors = Vec::with_capacity(num_vectors);
    
    // Initial seed (NIST starts with zeros)
    let mut seed = [0u8; 48];
    
    for count in 0..num_vectors {
        // Generate entropy seed for this iteration
        let entropy = generate_entropy_seed(count, &seed);
        
        // Create DRBG with this seed
        let mut drbg = NistCtrDrbg::new_for_kat(&entropy)?;
        
        // Generate message of varying length
        let mlen = (count * 13 + 7) % 1024; // NIST pattern for message lengths
        let mut msg = vec![0u8; mlen];
        if mlen > 0 {
            drbg.randombytes(&mut msg)?;
        }
        
        // Generate keypair using DRBG
        let (pk_bytes, sk_bytes) = generate_keypair_with_drbg(&mut drbg)?;
        
        // Deserialize keys from generated bytes
        let public_key = deserialize_public_key(&pk_bytes)?;
        let private_key = deserialize_private_key(&sk_bytes)?;
        
        // Sign message
        let signature = sign_with_drbg(&msg, &private_key, &mut drbg)?;
        
        // Create signed message (NIST format: signature || message)
        let mut sm = Vec::with_capacity(signature.len() + msg.len());
        sm.extend_from_slice(&signature);
        sm.extend_from_slice(&msg);
        
        // Verify signature
        match verify(&msg, &signature, &public_key) {
            Ok(true) => {},
            Ok(false) | Err(_) => {
                return Err(Falcon512Error::VerificationFailed);
            }
        }
        
        // Store vector
        vectors.push(KatVector {
            count,
            seed: entropy,
            mlen,
            msg: msg.clone(),
            pk: pk_bytes.clone(),
            sk: sk_bytes.clone(),
            smlen: sm.len(),
            sm,
        });
        
        // Update seed for next iteration (NIST incremental update)
        update_seed(&mut seed, &entropy);
    }
    
    Ok(vectors)
}

/// Generate entropy seed for a self-consistency KAT iteration.
/// In-repo SHA-256 scheme (NOT the NIST AES-CTR-DRBG seed method).
fn generate_entropy_seed(count: usize, prev_seed: &[u8; 48]) -> [u8; 48] {
    let mut hasher = Sha256Hasher::new();
    
    // Hash: counter || previous seed
    hasher.update(&(count as u32).to_le_bytes());
    hasher.update(prev_seed);
    
    let hash = hasher.finalize();
    
    // Expand to 48 bytes using second hash
    let mut seed = [0u8; 48];
    seed[..32].copy_from_slice(&hash);
    
    // Hash again for remaining bytes
    let mut hasher2 = Sha256Hasher::new();
    hasher2.update(&hash);
    hasher2.update(b"KAT");
    let hash2 = hasher2.finalize();
    seed[32..48].copy_from_slice(&hash2[..16]);
    
    seed
}

/// Update seed for next iteration
fn update_seed(seed: &mut [u8; 48], entropy: &[u8; 48]) {
    // NIST method: XOR with entropy and increment
    for i in 0..48 {
        seed[i] ^= entropy[i];
    }
    
    // Increment as big-endian counter
    for i in (0..48).rev() {
        seed[i] = seed[i].wrapping_add(1);
        if seed[i] != 0 {
            break;
        }
    }
}

/// Generate keypair using NIST DRBG
fn generate_keypair_with_drbg(drbg: &mut NistCtrDrbg) -> Result<(Vec<u8>, Vec<u8>)> {
    // Create custom RNG that uses DRBG
    struct DrbgRng<'a> {
        drbg: &'a mut NistCtrDrbg,
    }
    
    impl<'a> rand_core::RngCore for DrbgRng<'a> {
        fn next_u32(&mut self) -> u32 {
            let mut bytes = [0u8; 4];
            self.fill_bytes(&mut bytes);
            u32::from_le_bytes(bytes)
        }
        
        fn next_u64(&mut self) -> u64 {
            let mut bytes = [0u8; 8];
            self.fill_bytes(&mut bytes);
            u64::from_le_bytes(bytes)
        }
        
        fn fill_bytes(&mut self, dest: &mut [u8]) {
            self.drbg.randombytes(dest).unwrap();
        }
        
        fn try_fill_bytes(&mut self, dest: &mut [u8]) -> core::result::Result<(), rand_core::Error> {
            self.fill_bytes(dest);
            Ok(())
        }
    }
    
    impl<'a> rand_core::CryptoRng for DrbgRng<'a> {}
    
    let mut rng = DrbgRng { drbg };
    
    // Try multiple times for keygen as it can also fail due to rejection sampling
    let mut keypair = None;
    for attempt in 0..10 {
        match generate_keypair(&mut rng) {
            Ok(kp) => {
                keypair = Some(kp);
                break;
            }
            Err(_) if attempt < 9 => {
                // Continue trying
                continue;
            }
            Err(e) => return Err(e),
        }
    }
    
    let keypair = keypair.ok_or(Falcon512Error::KeyGenerationFailed)?;
    
    // Serialize keypair to bytes using proper serialization
    let pk = serialize_public_key(&keypair.public_key);
    let sk = serialize_private_key(&keypair.private_key);
    
    Ok((pk, sk))
}

/// Sign message using NIST DRBG
fn sign_with_drbg(msg: &[u8], sk: &crate::PrivateKey, drbg: &mut NistCtrDrbg) -> Result<Vec<u8>> {
    // Create custom RNG that uses DRBG
    struct DrbgRng<'a> {
        drbg: &'a mut NistCtrDrbg,
    }
    
    impl<'a> rand_core::RngCore for DrbgRng<'a> {
        fn next_u32(&mut self) -> u32 {
            let mut bytes = [0u8; 4];
            self.fill_bytes(&mut bytes);
            u32::from_le_bytes(bytes)
        }
        
        fn next_u64(&mut self) -> u64 {
            let mut bytes = [0u8; 8];
            self.fill_bytes(&mut bytes);
            u64::from_le_bytes(bytes)
        }
        
        fn fill_bytes(&mut self, dest: &mut [u8]) {
            self.drbg.randombytes(dest).unwrap();
        }
        
        fn try_fill_bytes(&mut self, dest: &mut [u8]) -> core::result::Result<(), rand_core::Error> {
            self.fill_bytes(dest);
            Ok(())
        }
    }
    
    impl<'a> rand_core::CryptoRng for DrbgRng<'a> {}
    
    let mut rng = DrbgRng { drbg };
    
    // Use persistent mode for KAT generation to handle non-deterministic failures
    let config = crate::retry_strategy::SigningConfig::from_mode(
        crate::retry_strategy::SigningMode::Persistent
    );
    let result = crate::retry_strategy::sign_with_retry(msg, sk, &mut rng, &config)?;
    Ok(result.signature)
}

/// Validate against known NIST KAT vectors
pub fn validate_kat_vectors(vectors: &[KatVector], expected: &[KatVector]) -> Result<bool> {
    if vectors.len() != expected.len() {
        return Ok(false);
    }
    
    for (generated, expected) in vectors.iter().zip(expected.iter()) {
        // Check all fields match
        if generated.count != expected.count ||
           generated.seed != expected.seed ||
           generated.mlen != expected.mlen ||
           generated.msg != expected.msg ||
           generated.pk != expected.pk ||
           generated.sk != expected.sk ||
           generated.smlen != expected.smlen ||
           generated.sm != expected.sm {
            return Ok(false);
        }
    }
    
    Ok(true)
}

/// Serialize public key to bytes
fn serialize_public_key(pk: &PublicKey) -> Vec<u8> {
    pk.to_bytes()
}

/// Serialize private key to bytes
fn serialize_private_key(sk: &PrivateKey) -> Vec<u8> {
    sk.to_bytes()
}

/// Deserialize public key from bytes
fn deserialize_public_key(bytes: &[u8]) -> Result<PublicKey> {
    PublicKey::from_bytes(bytes)
}

/// Deserialize private key from bytes
fn deserialize_private_key(bytes: &[u8]) -> Result<PrivateKey> {
    PrivateKey::from_bytes(bytes)
}

/// Load NIST KAT vectors from file
pub fn load_nist_kat_vectors() -> Result<Vec<KatVector>> {
    // Fail closed until official vectors are available instead of silently
    // claiming that "zero vectors" is a valid load result.
    Err(Falcon512Error::NotImplemented)
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_kat_generation() {
        // Generate a few test vectors
        let vectors = generate_kat_vectors(3).unwrap();
        assert_eq!(vectors.len(), 3);
        
        // Check vectors have expected structure
        for (i, vec) in vectors.iter().enumerate() {
            assert_eq!(vec.count, i);
            assert_eq!(vec.seed.len(), 48);
            assert_eq!(vec.msg.len(), vec.mlen);
            assert_eq!(vec.pk.len(), crate::constants::PUBLIC_KEY_SIZE);
            // sk.to_bytes() uses NIST reference format (1281 bytes: f:6bit + g:6bit + F:8bit)
            assert_eq!(vec.sk.len(), 1281);
            assert_eq!(vec.sm.len(), vec.smlen);
        }
    }
    
    #[test]
    fn test_loading_unavailable_official_vectors_fails_closed() {
        assert!(matches!(
            load_nist_kat_vectors(),
            Err(Falcon512Error::NotImplemented)
        ));
    }

    #[test]
    fn test_entropy_seed_generation() {
        let initial = [0u8; 48];
        let seed1 = generate_entropy_seed(0, &initial);
        let seed2 = generate_entropy_seed(1, &seed1);
        
        // Seeds should be different
        assert_ne!(seed1, seed2);
        
        // Seeds should be deterministic
        let seed1_again = generate_entropy_seed(0, &initial);
        assert_eq!(seed1, seed1_again);
    }
    
    #[test]
    fn test_seed_update() {
        let mut seed = [0u8; 48];
        let entropy = [0xFFu8; 48];
        
        update_seed(&mut seed, &entropy);
        
        // Should have XORed and incremented (big-endian)
        // Starting with all 0x00, XOR with 0xFF gives all 0xFF
        // Incrementing 0xFFFFFF...FFFF by 1 gives 0x000000...0000 (overflow)
        for i in 0..48 {
            assert_eq!(seed[i], 0x00, "seed[{}] should be 0x00 after overflow", i);
        }
    }
}
