//! Sign-side byte-equality gate for AIMer (deterministic KAT).
//!
//! The verify gate (`aimer_upstream_kat.rs`) proves we ACCEPT genuine upstream
//! signatures. This gate proves the stronger property that we PRODUCE them: for
//! each genuine upstream KAT record we seed a NIST AES-256-CTR-DRBG with the
//! record seed, draw `pt`/`iv` (keygen) then `rho` (sign) exactly as upstream's
//! `crypto_sign_keypair` + `crypto_sign` do, and assert the resulting `pk`,
//! `sk`, and signature bytes equal the vendored upstream `.rsp` byte-for-byte.
//!
//! Reports the FIRST divergence (pk → sk → sig) so a failure pinpoints whether
//! keygen, the DRBG draw order, or the sign path is at fault.
//!
//! Skips loudly when the genuine vectors are not vendored (same contract as the
//! verify gate). See `test-vectors/aimer-upstream/README.md`.

use std::path::PathBuf;

use metamui_aes_ctr_drbg::NistKatRng;
use metamui_aimer::signing::{keypair_from_pt_iv, sign_with_rho};
use metamui_aimer::{
    Aim2erI, Aim2erIF, Aim2erIII, Aim2erIIIF, Aim2erV, Aim2erVF, AimerParams,
};

const SELFGEN_MARKER: &str = "Generated by tools/aimer-kat-generator";
const UPSTREAM_ROOT: &[&str] = &["..", "..", "test-vectors", "aimer-upstream", "v2.1"];

struct Rec {
    seed: Vec<u8>,
    pk: Vec<u8>,
    sk: Vec<u8>,
    msg: Vec<u8>,
    sm: Vec<u8>,
    mlen: usize,
}

fn upstream_path(rel: &str) -> PathBuf {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let mut p = PathBuf::from(manifest_dir);
    for seg in UPSTREAM_ROOT {
        p.push(seg);
    }
    p.push(rel);
    p
}

/// Parse the fields needed for the sign KAT: seed, pk, sk, msg, sm, mlen.
fn parse_rsp(content: &str) -> Vec<Rec> {
    let mut recs = Vec::new();
    let (mut seed, mut pk, mut sk, mut msg, mut sm, mut mlen) =
        (None, None, None, None, None, None);
    let flush = |seed: &mut Option<Vec<u8>>,
                 pk: &mut Option<Vec<u8>>,
                 sk: &mut Option<Vec<u8>>,
                 msg: &mut Option<Vec<u8>>,
                 sm: &mut Option<Vec<u8>>,
                 mlen: &mut Option<usize>,
                 out: &mut Vec<Rec>| {
        if let (Some(s), Some(p), Some(k), Some(m), Some(smv), Some(ml)) =
            (seed.take(), pk.take(), sk.take(), msg.take(), sm.take(), mlen.take())
        {
            out.push(Rec { seed: s, pk: p, sk: k, msg: m, sm: smv, mlen: ml });
        }
    };
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            flush(&mut seed, &mut pk, &mut sk, &mut msg, &mut sm, &mut mlen, &mut recs);
            continue;
        }
        if let Some(v) = line.strip_prefix("seed = ") {
            seed = Some(hex::decode(v).expect("bad seed hex"));
        } else if let Some(v) = line.strip_prefix("pk = ") {
            pk = Some(hex::decode(v).expect("bad pk hex"));
        } else if let Some(v) = line.strip_prefix("sk = ") {
            sk = Some(hex::decode(v).expect("bad sk hex"));
        } else if let Some(v) = line.strip_prefix("msg = ") {
            msg = Some(hex::decode(v).expect("bad msg hex"));
        } else if let Some(v) = line.strip_prefix("sm = ") {
            sm = Some(hex::decode(v).expect("bad sm hex"));
        } else if let Some(v) = line.strip_prefix("mlen = ") {
            mlen = Some(v.parse::<usize>().expect("bad mlen"));
        }
    }
    flush(&mut seed, &mut pk, &mut sk, &mut msg, &mut sm, &mut mlen, &mut recs);
    recs
}

fn hexs(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

fn run_sign_gate<P: AimerParams>(rel_path: &str, label: &str) {
    let path = upstream_path(rel_path);
    // The genuine-upstream KAT is tracked in this repo: its absence is a
    // broken checkout, not a skip (audit A28) — FAIL instead of going green.
    let content = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("{label}: genuine-upstream KAT missing at {} ({e})", path.display())
    });
    assert!(
        !content.contains(SELFGEN_MARKER),
        "{label}: {} is a SELF-GENERATED vector, not genuine upstream.",
        path.display()
    );

    let fs = P::FIELD_SIZE;
    let sec_bytes = P::SECURITY_BITS / 8;
    let recs = parse_rsp(&content);
    assert!(!recs.is_empty(), "{label}: no records parsed");

    let mut ok = 0usize;
    for (i, r) in recs.iter().enumerate() {
        // Reproduce the upstream KAT RNG flow: seed → pt → iv (keygen) → rho (sign).
        let mut rng = NistKatRng::new(&r.seed).expect("DRBG init");
        let pt = rng.randombytes(fs).expect("draw pt");
        let iv = rng.randombytes(fs).expect("draw iv"); // AIM2_IV_SIZE == FIELD_SIZE

        let (pk, sk) = keypair_from_pt_iv::<P>(&pt, &iv).expect("keypair");

        // pk = iv ‖ ct ; sk = pt ‖ iv ‖ ct
        let pk_bytes = [pk.iv.clone(), pk.ct.clone()].concat();
        assert_eq!(
            hexs(&pk_bytes), hexs(&r.pk),
            "{label} rec {i}: KEYGEN pk mismatch (DRBG or aim2 keygen diverges)"
        );
        let sk_bytes = [sk.sk.clone(), sk.pk.iv.clone(), sk.pk.ct.clone()].concat();
        assert_eq!(
            hexs(&sk_bytes), hexs(&r.sk),
            "{label} rec {i}: KEYGEN sk mismatch"
        );

        let rho = rng.randombytes(sec_bytes).expect("draw rho");
        let sig = sign_with_rho::<P>(&r.msg, &sk, &rho).expect("sign");
        let sig_bytes = sig.to_bytes::<P>();

        let exp_sig = &r.sm[r.mlen..];
        assert_eq!(
            hexs(&sig_bytes), hexs(exp_sig),
            "{label} rec {i}: SIGN byte mismatch (sign path diverges from upstream)"
        );
        ok += 1;
    }
    eprintln!("PASS {label}: {ok}/{} records keygen+sign byte-equal to upstream", recs.len());
}

#[test]
fn sign_kat_aimer128s() { run_sign_gate::<Aim2erI>("aimer-128s/PQCsignKAT_48.rsp", "AIMer-128s"); }
#[test]
fn sign_kat_aimer128f() { run_sign_gate::<Aim2erIF>("aimer-128f/PQCsignKAT_48.rsp", "AIMer-128f"); }
#[test]
fn sign_kat_aimer192s() { run_sign_gate::<Aim2erIII>("aimer-192s/PQCsignKAT_72.rsp", "AIMer-192s"); }
#[test]
fn sign_kat_aimer192f() { run_sign_gate::<Aim2erIIIF>("aimer-192f/PQCsignKAT_72.rsp", "AIMer-192f"); }
#[test]
fn sign_kat_aimer256s() { run_sign_gate::<Aim2erV>("aimer-256s/PQCsignKAT_96.rsp", "AIMer-256s"); }
#[test]
fn sign_kat_aimer256f() { run_sign_gate::<Aim2erVF>("aimer-256f/PQCsignKAT_96.rsp", "AIMer-256f"); }
