//! Genuine-upstream conformance gate for AIMer specification v3.
//!
//! Replays each record of the authors' `PQCsignKAT_*.rsp` (NIST AES-256-CTR-DRBG,
//! no DF, `randombytes_init(seed48)`): `crypto_sign_keypair` draws `pt` then `iv`
//! and retries on a zero S-box input; `crypto_sign` then draws the λ/8-byte
//! signing randomness. Asserts pk, sk and `sm = m ‖ sig` byte-for-byte, that the
//! signature verifies, and that a flipped byte does not. The oracle files are
//! tracked in this repo: a missing file fails the gate.

use std::path::PathBuf;

use metamui_aes_ctr_drbg::NistKatRng;
use metamui_aimer::v3::{
    keypair_from_pt_iv, sign_with_rnd, verify_with_ctx, Aimer128f, Aimer128s, Aimer192f, Aimer192s,
    Aimer256f, Aimer256s, AimerV3Params, V3Error,
};

const SELFGEN_MARKER: &str = "Generated by tools/aimer-kat-generator";
const MIN_RECORDS: usize = 5;

struct Rec {
    count: usize,
    seed: Vec<u8>,
    msg: Vec<u8>,
    pk: Vec<u8>,
    sk: Vec<u8>,
    sm: Vec<u8>,
}

fn upstream_path(rel: &str) -> PathBuf {
    let mut p = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    for seg in ["..", "..", "test-vectors", "aimer-upstream", rel] {
        p.push(seg);
    }
    p
}

fn parse_rsp(content: &str) -> Vec<Rec> {
    let mut recs = Vec::new();
    let mut cur: Option<Rec> = None;
    for line in content.lines() {
        let line = line.trim();
        if let Some(v) = line.strip_prefix("count = ") {
            if let Some(r) = cur.take() {
                recs.push(r);
            }
            cur = Some(Rec { count: v.parse().unwrap(), seed: vec![], msg: vec![], pk: vec![], sk: vec![], sm: vec![] });
            continue;
        }
        let Some(r) = cur.as_mut() else { continue };
        if let Some(v) = line.strip_prefix("seed = ") {
            r.seed = hex::decode(v).unwrap();
        } else if let Some(v) = line.strip_prefix("msg = ") {
            r.msg = hex::decode(v).unwrap();
        } else if let Some(v) = line.strip_prefix("pk = ") {
            r.pk = hex::decode(v).unwrap();
        } else if let Some(v) = line.strip_prefix("sk = ") {
            r.sk = hex::decode(v).unwrap();
        } else if let Some(v) = line.strip_prefix("sm = ") {
            r.sm = hex::decode(v).unwrap();
        }
    }
    if let Some(r) = cur.take() {
        recs.push(r);
    }
    recs
}

fn run_gate<P: AimerV3Params>(rel: &str) {
    let path = upstream_path(rel);
    let content = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("{}: cannot read {} ({e}); the oracle is tracked in this repo", P::NAME, path.display()));
    assert!(!content.contains(SELFGEN_MARKER), "{}: self-generated file is not an oracle", P::NAME);
    let recs = parse_rsp(&content);
    assert!(recs.len() >= MIN_RECORDS, "{}: expected at least {MIN_RECORDS} records, got {}", P::NAME, recs.len());

    for r in &recs {
        let mut rng = NistKatRng::new(&r.seed).expect("DRBG init");
        let (pk, sk) = loop {
            let pt = rng.randombytes(P::FB).unwrap();
            let iv = rng.randombytes(P::FB).unwrap();
            match keypair_from_pt_iv::<P>(&pt, &iv) {
                Ok(kp) => break kp,
                Err(V3Error::ZeroSboxInput) => continue,
                Err(e) => panic!("{} count={}: keygen error {e}", P::NAME, r.count),
            }
        };
        assert_eq!(pk, r.pk, "{} count={}: pk mismatch", P::NAME, r.count);
        assert_eq!(sk, r.sk, "{} count={}: sk mismatch", P::NAME, r.count);

        let rnd = rng.randombytes(P::FB).unwrap();
        let sig = sign_with_rnd::<P>(&r.msg, &[], &rnd, &sk).expect("sign");
        let mut sm = r.msg.clone();
        sm.extend_from_slice(&sig);
        assert_eq!(sm.len(), r.sm.len(), "{} count={}: smlen mismatch", P::NAME, r.count);
        let first_diff = sm.iter().zip(r.sm.iter()).position(|(a, b)| a != b);
        assert!(first_diff.is_none(), "{} count={}: sm differs first at byte {:?} (msg is {} bytes)", P::NAME, r.count, first_diff, r.msg.len());

        assert!(verify_with_ctx::<P>(&sig, &r.msg, &[], &pk), "{} count={}: genuine signature rejected", P::NAME, r.count);
        let mut bad = sig.clone();
        bad[P::FB + P::COMMIT + 1] ^= 0x01; // inside h_2
        assert!(!verify_with_ctx::<P>(&bad, &r.msg, &[], &pk), "{} count={}: tampered signature accepted", P::NAME, r.count);
    }
    eprintln!("PASS {}: {}/{} records keygen+sign+verify byte-exact", P::NAME, recs.len(), recs.len());
}

#[test]
fn v3_upstream_aimer128s() { run_gate::<Aimer128s>("aimer-128s/PQCsignKAT_48.rsp"); }
#[test]
fn v3_upstream_aimer128f() { run_gate::<Aimer128f>("aimer-128f/PQCsignKAT_48.rsp"); }
#[test]
fn v3_upstream_aimer192s() { run_gate::<Aimer192s>("aimer-192s/PQCsignKAT_72.rsp"); }
#[test]
fn v3_upstream_aimer192f() { run_gate::<Aimer192f>("aimer-192f/PQCsignKAT_72.rsp"); }
#[test]
fn v3_upstream_aimer256s() { run_gate::<Aimer256s>("aimer-256s/PQCsignKAT_96.rsp"); }
#[test]
fn v3_upstream_aimer256f() { run_gate::<Aimer256f>("aimer-256f/PQCsignKAT_96.rsp"); }
