//! Genuine-upstream conformance gate for AIMer.
//!
//! Unlike `kat_vectors.rs` (which re-signs with our own impl and self-verifies)
//! and `aimer_v2_kat.rs` (which verifies vectors that the in-repo C reference
//! generated — a circular check), this gate verifies our verifier against the
//! **unmodified Samsung SDS upstream** answer files.
//!
//! It is the only test that can fail when our AIMer diverges from canonical
//! AIMer at the algorithm level. See `test-vectors/aimer-upstream/README.md`
//! for how to vendor the genuine `.rsp` files.
//!
//! Behaviour per parameter set:
//!   * upstream file absent      → FAIL (a tracked vector is missing: broken checkout)
//!   * upstream file self-gen'd  → FAIL (anti-circularity guard)
//!   * upstream file genuine     → verify EVERY record; any rejection fails.
//!
//! There is deliberately **no self-sign fallback**: the whole point is to test
//! foreign signatures, so a verify failure must surface, never be papered over.
//!
//! ## STATUS: PASSING — Rust verify conforms to genuine upstream (2026-06-01)
//!
//! Genuine upstream KAT (trimmed, 5 records/variant) is vendored under
//! `test-vectors/aimer-upstream/` from samsungsds AIMer commit
//! `e47c497f3552c234e0ca8368df9bb629af9608ce`. This gate verifies every
//! record's `sm` and now passes **5/5 across all six variants**.
//!
//! The fix (commit on 2026-06-01) was two divergences in the `mu` pre-hash
//! `H₀` vs. the older in-repo reference this port had mirrored:
//!   1. per-variant `H0_PREFIX` (was hardcoded `0x00` — wrong for 5 of 6 sets),
//!   2. the `ctxlen = 0x00` context byte between `ct` and the message (the spec
//!      adopted the NIST-style context API; the old vintage omitted it).
//! `mu` feeds `h_1` → `expand_h1` → `h_2`, so that single wrong byte rejected
//! every signature; correcting it fixed the whole verify chain.

use std::path::PathBuf;

/// Why a missing vector file fails instead of skipping.
const KAT_ABSENCE_NOTE: &str = "The vectors are tracked in this repo, so their absence is a broken checkout, not an environment quirk — and a green run that verified nothing is exactly what this gate exists to prevent.";

use metamui_aimer::{
    signing::{PublicKey, Signature},
    Aim2erI, Aim2erIF, Aim2erIII, Aim2erIIIF, Aim2erV, Aim2erVF, Aimer, AimerParams,
};

// ---------------------------------------------------------------------------
// Marker that brands a vector file as locally generated (and therefore unfit
// as an upstream conformance source). Kept identical to the string emitted by
// tools/aimer-kat-generator so the guard tracks it.
// ---------------------------------------------------------------------------
const SELFGEN_MARKER: &str = "Generated by tools/aimer-kat-generator";

const UPSTREAM_ROOT: &[&str] = &["..", "..", "test-vectors", "aimer-upstream", "v2.1"];

struct KatEntry {
    pk_bytes: Vec<u8>,
    msg: Vec<u8>,
    sm_bytes: Vec<u8>,
    mlen: usize,
}

/// Resolve `test-vectors/aimer-upstream/<rel>` relative to the crate manifest.
fn upstream_path(rel: &str) -> PathBuf {
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let mut p = PathBuf::from(manifest_dir);
    for seg in UPSTREAM_ROOT {
        p.push(seg);
    }
    p.push(rel);
    p
}

/// Minimal PQClean `.rsp` parser. Only the fields needed to verify a foreign
/// signature are extracted: `pk`, `msg`, `sm`, `mlen` (seed/sk/smlen ignored).
fn parse_rsp(content: &str) -> Vec<KatEntry> {
    let mut entries = Vec::new();
    let (mut pk, mut msg, mut sm, mut mlen) = (None, None, None, None);

    let flush = |pk: &mut Option<Vec<u8>>,
                     msg: &mut Option<Vec<u8>>,
                     sm: &mut Option<Vec<u8>>,
                     mlen: &mut Option<usize>,
                     out: &mut Vec<KatEntry>| {
        if let (Some(p), Some(m), Some(s), Some(ml)) =
            (pk.take(), msg.take(), sm.take(), mlen.take())
        {
            out.push(KatEntry { pk_bytes: p, msg: m, sm_bytes: s, mlen: ml });
        }
    };

    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            flush(&mut pk, &mut msg, &mut sm, &mut mlen, &mut entries);
            continue;
        }
        if let Some(v) = line.strip_prefix("pk = ") {
            pk = Some(hex::decode(v).expect("bad pk hex"));
        } else if let Some(v) = line.strip_prefix("msg = ") {
            msg = Some(hex::decode(v).expect("bad msg hex"));
        } else if let Some(v) = line.strip_prefix("sm = ") {
            sm = Some(hex::decode(v).expect("bad sm hex"));
        } else if let Some(v) = line.strip_prefix("mlen = ") {
            mlen = Some(v.parse::<usize>().expect("bad mlen"));
        }
    }
    flush(&mut pk, &mut msg, &mut sm, &mut mlen, &mut entries);
    entries
}

/// Split an upstream `pk` blob into the AIMer `PublicKey` (`iv || ct`).
fn reconstruct_pk<P: AimerParams>(pk_bytes: &[u8]) -> PublicKey {
    assert_eq!(
        pk_bytes.len(),
        P::PUBLIC_KEY_SIZE,
        "upstream pk size {} != expected {}",
        pk_bytes.len(),
        P::PUBLIC_KEY_SIZE
    );
    PublicKey {
        iv: pk_bytes[..P::FIELD_SIZE].to_vec(),
        ct: pk_bytes[P::FIELD_SIZE..].to_vec(),
    }
}

/// The gate body, generic over a parameter set `P`.
fn run_upstream_gate<P: AimerParams>(rel_path: &str, label: &str) {
    let path = upstream_path(rel_path);

    // ---- absent → FAIL loudly -------------------------------------------
    let content = match std::fs::read_to_string(&path) {
        Ok(c) => c,
        Err(e) => {
            panic!(
                "{label}: genuine-upstream KAT not readable at {} ({e}). \
                 See test-vectors/aimer-upstream/README.md. {KAT_ABSENCE_NOTE}",
                path.display()
            );
        }
    };

    // ---- present but self-generated → fail (anti-circularity) -----------
    assert!(
        !content.contains(SELFGEN_MARKER),
        "{label}: {} is a SELF-GENERATED vector ('{}'), not genuine upstream. \
         Verifying against it is circular. Replace it with the real Samsung SDS file.",
        path.display(),
        SELFGEN_MARKER
    );

    // ---- present and genuine → verify every record ----------------------
    let entries = parse_rsp(&content);
    assert!(!entries.is_empty(), "{label}: no records parsed from {}", path.display());

    let mut accepted = 0usize;
    let mut first_failure: Option<String> = None;

    for (i, e) in entries.iter().enumerate() {
        // sm = msg || signature_bytes
        if e.sm_bytes.len() < e.mlen || &e.sm_bytes[..e.mlen] != e.msg.as_slice() {
            first_failure.get_or_insert_with(|| {
                format!("record {i}: sm prefix does not equal msg")
            });
            continue;
        }
        let sig_bytes = &e.sm_bytes[e.mlen..];
        let pk = reconstruct_pk::<P>(&e.pk_bytes);

        // A wire-format rejection at deserialize time is itself a divergence.
        let sig = match Signature::from_bytes::<P>(sig_bytes) {
            Ok(s) => s,
            Err(err) => {
                first_failure.get_or_insert_with(|| {
                    format!("record {i}: Signature::from_bytes rejected upstream bytes: {err:?}")
                });
                continue;
            }
        };

        match Aimer::<P>::verify(&e.msg, &sig, &pk) {
            Ok(true) => accepted += 1,
            Ok(false) => {
                first_failure.get_or_insert_with(|| {
                    format!("record {i}: verifier returned false for genuine upstream signature")
                });
            }
            Err(err) => {
                first_failure.get_or_insert_with(|| {
                    format!("record {i}: verify errored on upstream signature: {err:?}")
                });
            }
        }
    }

    if let Some(reason) = first_failure {
        panic!(
            "{label}: {accepted}/{} genuine upstream signatures accepted — \
             ALGORITHM DIVERGENCE from canonical AIMer.\n  first failure: {reason}",
            entries.len()
        );
    }

    eprintln!("PASS {label}: {accepted}/{} genuine upstream signatures accepted", entries.len());
}

// ---------------------------------------------------------------------------
// One test per parameter set. Filenames match PQClean's KAT naming.
// ---------------------------------------------------------------------------

#[test]
fn upstream_verify_aimer128s() {
    run_upstream_gate::<Aim2erI>("aimer-128s/PQCsignKAT_48.rsp", "AIMer-128s");
}

#[test]
fn upstream_verify_aimer128f() {
    run_upstream_gate::<Aim2erIF>("aimer-128f/PQCsignKAT_48.rsp", "AIMer-128f");
}

#[test]
fn upstream_verify_aimer192s() {
    run_upstream_gate::<Aim2erIII>("aimer-192s/PQCsignKAT_72.rsp", "AIMer-192s");
}

#[test]
fn upstream_verify_aimer192f() {
    run_upstream_gate::<Aim2erIIIF>("aimer-192f/PQCsignKAT_72.rsp", "AIMer-192f");
}

#[test]
fn upstream_verify_aimer256s() {
    run_upstream_gate::<Aim2erV>("aimer-256s/PQCsignKAT_96.rsp", "AIMer-256s");
}

#[test]
fn upstream_verify_aimer256f() {
    run_upstream_gate::<Aim2erVF>("aimer-256f/PQCsignKAT_96.rsp", "AIMer-256f");
}
