//! HAETAE-2 cross-language consensus KAT.
//!
//! Drives the deterministic `*_internal` API from the genuine HAETAE 1.1.2
//! (KS X 123456) consensus fixtures in `test-vectors/haetae/haetae2_kat.json`
//! (regenerated by `test-vectors/haetae/regenerate_consensus.py` from the
//! authoritative upstream KAT) and asserts pk/sk/sig byte-for-byte plus a
//! successful verify. Each vector carries the DRBG-derived `keygen_seed`,
//! `rnd` and context `pre`, so no DRBG replay is needed here.
//!
//! Mode-2 specific (sizes + `haetae2_kat.json`); only compiled under the
//! `haetae2` feature.
#![cfg(feature = "haetae2")]

use metamui_haetae::params::{CRYPTO_BYTES, CRYPTO_PUBLICKEYBYTES, CRYPTO_SECRETKEYBYTES};
use metamui_haetae::sign::{
    crypto_sign_keypair_internal, crypto_sign_signature_internal, crypto_sign_verify_internal,
};
use serde::Deserialize;

// ---------------------------------------------------------------------------
// JSON schema (genuine 1.1.2 consensus)
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct KatFile {
    #[allow(dead_code)]
    algorithm: String,
    #[allow(dead_code)]
    parameter_set: String,
    test_vectors: Vec<TestVector>,
}

#[derive(Deserialize)]
struct TestVector {
    count: usize,
    keygen_seed: String,
    rnd: String,
    pre: String,
    #[allow(dead_code)]
    mlen: usize,
    msg: String,
    pk: String,
    sk: String,
    sig: String,
}

fn load_vectors() -> KatFile {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let path = format!("{}/../../test-vectors/haetae/haetae2_kat.json", manifest_dir);
    let data = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Failed to read {}: {}", path, e));
    serde_json::from_str(&data).unwrap_or_else(|e| panic!("Failed to parse KAT JSON: {}", e))
}

fn hx(s: &str) -> Vec<u8> {
    hex::decode(s).expect("invalid hex")
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

/// Re-derive every vector through keygen+sign+verify and assert byte-exactness.
#[test]
fn haetae2_kat_byte_exact() {
    let kat = load_vectors();
    assert!(
        kat.test_vectors.len() >= 3,
        "Expected at least 3 test vectors, got {}",
        kat.test_vectors.len()
    );

    for tv in &kat.test_vectors {
        let seed_arr: [u8; 32] = hx(&tv.keygen_seed).try_into().expect("keygen_seed not 32B");
        let rnd_arr: [u8; 32] = hx(&tv.rnd).try_into().expect("rnd not 32B");
        let pre = hx(&tv.pre);
        let msg = hx(&tv.msg);
        let exp_pk = hx(&tv.pk);
        let exp_sk = hx(&tv.sk);
        let exp_sig = hx(&tv.sig);

        let mut pk = [0u8; CRYPTO_PUBLICKEYBYTES];
        let mut sk = [0u8; CRYPTO_SECRETKEYBYTES];
        assert_eq!(crypto_sign_keypair_internal(&mut pk, &mut sk, &seed_arr), 0);
        assert_eq!(pk.as_slice(), exp_pk.as_slice(), "count={}: pk mismatch", tv.count);
        assert_eq!(sk.as_slice(), exp_sk.as_slice(), "count={}: sk mismatch", tv.count);

        let mut sig = [0u8; CRYPTO_BYTES];
        let mut siglen = 0usize;
        assert_eq!(
            crypto_sign_signature_internal(&mut sig, &mut siglen, &msg, msg.len(), &pre, &rnd_arr, &sk),
            0
        );
        assert_eq!(siglen, CRYPTO_BYTES);
        assert_eq!(sig.as_slice(), exp_sig.as_slice(), "count={}: sig mismatch", tv.count);

        assert_eq!(
            crypto_sign_verify_internal(&sig, siglen, &msg, msg.len(), &pre, &pk),
            0,
            "count={}: verify failed",
            tv.count
        );
    }
}

/// A modified message must be rejected.
#[test]
fn haetae2_kat_verify_wrong_message() {
    let kat = load_vectors();
    let tv = &kat.test_vectors[0];
    let pre = hx(&tv.pre);
    let pk: [u8; CRYPTO_PUBLICKEYBYTES] = hx(&tv.pk).try_into().expect("pk size");
    let sig: [u8; CRYPTO_BYTES] = hx(&tv.sig).try_into().expect("sig size");
    let mut bad = hx(&tv.msg);
    bad[0] ^= 0x01;
    assert_ne!(
        crypto_sign_verify_internal(&sig, sig.len(), &bad, bad.len(), &pre, &pk),
        0,
        "verification should fail with modified message"
    );
}

/// A corrupted signature must be rejected.
#[test]
fn haetae2_kat_verify_corrupted_signature() {
    let kat = load_vectors();
    let tv = &kat.test_vectors[0];
    let pre = hx(&tv.pre);
    let pk: [u8; CRYPTO_PUBLICKEYBYTES] = hx(&tv.pk).try_into().expect("pk size");
    let msg = hx(&tv.msg);
    let mut sig: [u8; CRYPTO_BYTES] = hx(&tv.sig).try_into().expect("sig size");
    sig[0] ^= 0x01;
    assert_ne!(
        crypto_sign_verify_internal(&sig, sig.len(), &msg, msg.len(), &pre, &pk),
        0,
        "verification should fail with corrupted signature"
    );
}

/// KAT vector sizes match HAETAE-2 parameters.
#[test]
fn haetae2_kat_sizes() {
    let kat = load_vectors();
    let tv = &kat.test_vectors[0];
    assert_eq!(hx(&tv.pk).len(), CRYPTO_PUBLICKEYBYTES, "pk size mismatch");
    assert_eq!(hx(&tv.sig).len(), CRYPTO_BYTES, "HAETAE-2 signature should be 1474 bytes");
    assert_eq!(CRYPTO_BYTES, 1474);
}

/// Self-consistency: keygen → sign → verify round-trip with the public API.
#[test]
fn haetae2_self_roundtrip() {
    use metamui_haetae::api::KeyPair;

    let kp = KeyPair::generate().expect("keygen failed");
    let msg = b"HAETAE2 KAT self-consistency test";
    let sig = kp.sign(msg).expect("signing failed");
    kp.verify(msg, &sig).expect("verification of own signature failed");

    let bad_msg = b"tampered message";
    assert!(
        kp.verify(bad_msg, &sig).is_err(),
        "verification should fail with wrong message"
    );
}
