//! Sr25519 compliance regression net — asserts interoperability with
//! the canonical `w3f/schnorrkel` reference across three axes:
//!
//!   (A) **Public-key derivation parity** — `our.get_public_key(mini)`
//!        must equal the `schnorrkel::MiniSecretKey::expand(Ed25519)`-
//!        derived public key.
//!   (B) **Verifier parity** — our `verify(pk, ctx, msg, sig)` must
//!        accept signatures produced by real schnorrkel. (The KAT
//!        file's `signature` field was generated by schnorrkel 0.11.4
//!        via `examples/gen_schnorrkel_kat.rs`.)
//!   (C) **Signer parity** — signatures produced by `our.sign(mini,
//!        ctx, msg)` must be accepted by `schnorrkel::verify_simple`.
//!
//! All three are **expected to FAIL today** — that is the whole point
//! of Phase 1. This file is the regression net that will go green
//! once Phases 2–3 of
//! `documents/project/sr25519-compliance-plan.md` land.
//!
//! Do NOT mark individual axes ignored during remediation without also
//! recording the reason in the compliance plan. Losing a failing
//! assertion is worse than never having had it.

use metamui_sr25519::sr25519::Sr25519;
use schnorrkel::{ExpansionMode, MiniSecretKey, PublicKey as RefPublicKey, Signature as RefSignature};
use serde::Deserialize;
use std::fs;
use std::path::PathBuf;

#[derive(Deserialize)]
struct KatFile {
    #[allow(dead_code)]
    algorithm: String,
    #[allow(dead_code)]
    source: String,
    expansion_mode: String,
    vectors: Vec<KatVector>,
}

#[derive(Deserialize)]
struct KatVector {
    tc_id: u32,
    description: String,
    mini_secret: String,
    public_key: String,
    context: String,
    message: String,
    signature: String,
}

fn hex_decode(s: &str) -> Vec<u8> {
    if s.is_empty() {
        Vec::new()
    } else {
        hex::decode(s).expect("bad hex in KAT")
    }
}

fn kat_path() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("../../test-vectors/sr25519/sr25519-schnorrkel-kat.json");
    p
}

fn load_kat() -> KatFile {
    let path = kat_path();
    let data = fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "Sr25519 compliance KAT missing: {} ({e}).\n  The gate must never skip — \
             restore test-vectors/sr25519/sr25519-schnorrkel-kat.json (or regenerate \
             via `cargo run -p metamui-sr25519 --example gen_schnorrkel_kat`).",
            path.display()
        )
    });
    let kat: KatFile = serde_json::from_str(&data).expect("malformed KAT JSON");
    assert_eq!(
        kat.expansion_mode, "Ed25519",
        "KAT expansion_mode must be Ed25519 for Polkadot wire-compat"
    );
    assert!(!kat.vectors.is_empty(), "KAT file empty — regenerate via examples/gen_schnorrkel_kat.rs");
    kat
}

/// Report format used by every assertion below. Keeps the panic
/// message uniform so remediators can grep/filter by axis letter.
fn fail(tc_id: u32, axis: char, desc: &str, detail: &str) -> ! {
    panic!(
        "[Sr25519 compliance FAIL] axis={axis} tc_id={tc_id} — {desc}\n  detail: {detail}"
    );
}

// -----------------------------------------------------------------------
// Axis A — public-key derivation parity
// -----------------------------------------------------------------------
#[test]
fn axis_a_public_key_derivation_matches_schnorrkel() {
    let kat = load_kat();
    let mut passed = 0;
    let mut failed = 0;
    for v in &kat.vectors {
        let mini = hex_decode(&v.mini_secret);
        let expected_pk = hex_decode(&v.public_key);

        match Sr25519::get_public_key(&mini) {
            Ok(got) => {
                // `get_public_key` returns `Vec<u8>` in some builds
                // and `[u8; 32]` in others — normalise via slices.
                if got.as_ref() as &[u8] == expected_pk.as_slice() {
                    passed += 1;
                } else {
                    failed += 1;
                    eprintln!(
                        "  axis=A tc_id={} MISMATCH\n    expected: {}\n    got:      {}\n    desc:     {}",
                        v.tc_id,
                        hex::encode(&expected_pk),
                        hex::encode(got.as_ref() as &[u8]),
                        v.description
                    );
                }
            }
            Err(e) => {
                failed += 1;
                eprintln!("  axis=A tc_id={} ERROR: {:?}", v.tc_id, e);
            }
        }
    }
    eprintln!("\n[Sr25519 Axis A] {passed}/{} vectors matched", kat.vectors.len());
    if failed > 0 {
        fail(0, 'A', "public-key derivation parity",
            &format!("{failed} vector(s) diverged from schnorrkel expand(Ed25519)"));
    }
}

// -----------------------------------------------------------------------
// Axis B — our verifier accepts schnorrkel-produced signatures
// -----------------------------------------------------------------------
#[test]
fn axis_b_our_verifier_accepts_schnorrkel_signatures() {
    let kat = load_kat();
    let mut passed = 0;
    let mut failed = 0;
    for v in &kat.vectors {
        let pk = hex_decode(&v.public_key);
        let ctx = hex_decode(&v.context);
        let msg = hex_decode(&v.message);
        let sig_vec = hex_decode(&v.signature);
        let sig: [u8; 64] = match sig_vec.as_slice().try_into() {
            Ok(a) => a,
            Err(_) => {
                failed += 1;
                eprintln!("  axis=B tc_id={} bad signature length", v.tc_id);
                continue;
            }
        };

        match Sr25519::verify(&msg, &sig, &pk, &ctx) {
            Ok(true) => passed += 1,
            Ok(false) => {
                failed += 1;
                eprintln!(
                    "  axis=B tc_id={} REJECTED valid schnorrkel signature ({})",
                    v.tc_id, v.description
                );
            }
            Err(e) => {
                failed += 1;
                eprintln!("  axis=B tc_id={} ERROR: {:?}", v.tc_id, e);
            }
        }
    }
    eprintln!("\n[Sr25519 Axis B] {passed}/{} schnorrkel signatures accepted", kat.vectors.len());
    if failed > 0 {
        fail(0, 'B', "verifier parity",
            &format!("{failed} valid schnorrkel signature(s) rejected by our verifier"));
    }
}

// -----------------------------------------------------------------------
// Axis C — schnorrkel accepts signatures produced by our signer
// -----------------------------------------------------------------------
#[test]
fn axis_c_schnorrkel_accepts_our_signatures() {
    let kat = load_kat();
    let mut passed = 0;
    let mut failed = 0;
    for v in &kat.vectors {
        let mini = hex_decode(&v.mini_secret);
        let ctx = hex_decode(&v.context);
        let msg = hex_decode(&v.message);

        // Our signer → bytes.
        let our_sig = match Sr25519::sign(&msg, &mini, &ctx) {
            Ok(s) => s,
            Err(e) => {
                failed += 1;
                eprintln!("  axis=C tc_id={} our.sign ERROR: {:?}", v.tc_id, e);
                continue;
            }
        };

        // Schnorrkel-side verifier requires a PublicKey + Signature.
        // We deliberately re-expand from the mini_secret (rather than
        // trusting our.get_public_key) so Axis C stays orthogonal to
        // Axis A — if A fails, C can still surface an independent
        // signer-side bug.
        let mini_bytes: [u8; 32] = mini.as_slice().try_into().expect("mini_secret must be 32B");
        let ref_mini = MiniSecretKey::from_bytes(&mini_bytes).expect("ref mini from bytes");
        let ref_public = ref_mini.expand_to_public(ExpansionMode::Ed25519);

        let ref_sig = match RefSignature::from_bytes(&our_sig) {
            Ok(s) => s,
            Err(e) => {
                failed += 1;
                eprintln!(
                    "  axis=C tc_id={} our sig could not be parsed as schnorrkel::Signature: {:?}",
                    v.tc_id, e
                );
                continue;
            }
        };

        match ref_public.verify_simple(&ctx, &msg, &ref_sig) {
            Ok(()) => passed += 1,
            Err(e) => {
                failed += 1;
                eprintln!(
                    "  axis=C tc_id={} schnorrkel REJECTED our signature: {:?} ({})",
                    v.tc_id, e, v.description
                );
            }
        }

        // Spot-check: also verify against a PublicKey built from our
        // derived-pk bytes, to catch cases where our signer produces a
        // sig valid under schnorrkel's pk but not under our-pk-as-bytes.
        if let Ok(our_pk) = Sr25519::get_public_key(&mini) {
            if let Ok(as_ref_pk) = RefPublicKey::from_bytes(&our_pk) {
                // Not asserting — axis A owns pk-parity. This is just
                // a secondary probe; log divergence if it happens.
                if as_ref_pk.verify_simple(&ctx, &msg, &ref_sig).is_err() {
                    eprintln!(
                        "  axis=C tc_id={} note: sig valid under schnorrkel-pk but NOT under our-pk (A also broken)",
                        v.tc_id
                    );
                }
            }
        }
    }
    eprintln!("\n[Sr25519 Axis C] {passed}/{} our signatures accepted by schnorrkel", kat.vectors.len());
    if failed > 0 {
        fail(0, 'C', "signer parity",
            &format!("{failed} of our signature(s) rejected by schnorrkel"));
    }
}

// -----------------------------------------------------------------------
// Roundtrip sanity — internal consistency
// -----------------------------------------------------------------------
//
// Post-Phase-3, sign/verify are both Merlin+Ristretto based, so the
// internal roundtrip must hold for every KAT vector.
#[test]
fn roundtrip_sanity_our_sign_our_verify() {
    let kat = load_kat();
    for v in &kat.vectors {
        let mini = hex_decode(&v.mini_secret);
        let ctx = hex_decode(&v.context);
        let msg = hex_decode(&v.message);

        let sig = Sr25519::sign(&msg, &mini, &ctx).expect("our.sign");
        let pk = Sr25519::get_public_key(&mini).expect("our.get_public_key");
        let ok = Sr25519::verify(&msg, &sig, &pk, &ctx).expect("our.verify");
        assert!(ok, "tc_id={} internal roundtrip failed", v.tc_id);
    }
}
